--
-- PostgreSQL database dump
--

\restrict c5Sje78CGcDUu7Xujd9Gab5x7XbIxYnkoj2idrmAfceXEEPl6FIDbh7qof79W30

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    description character varying(2000),
    earned_at timestamp(6) with time zone NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT achievements_type_check CHECK (((type)::text = ANY ((ARRAY['COURSE_COMPLETED'::character varying, 'CERTIFICATION_EARNED'::character varying, 'SKILL_MASTERED'::character varying, 'MENTORSHIP_COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.achievements OWNER TO postgres;

--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_questions (
    id bigint NOT NULL,
    correct_option character varying(1) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    difficulty character varying(255) NOT NULL,
    explanation character varying(1000),
    option_a character varying(500) NOT NULL,
    option_b character varying(500) NOT NULL,
    option_c character varying(500) NOT NULL,
    option_d character varying(500) NOT NULL,
    question_text character varying(1000) NOT NULL,
    skill_id bigint NOT NULL,
    CONSTRAINT assessment_questions_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['UNAWARE'::character varying, 'BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[])))
);


ALTER TABLE public.assessment_questions OWNER TO postgres;

--
-- Name: assessment_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessment_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_reattempt_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_reattempt_requests (
    id bigint NOT NULL,
    attempts_at_request integer NOT NULL,
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    decided_at timestamp(6) with time zone,
    decision_note character varying(1000),
    reason character varying(1000) NOT NULL,
    status character varying(255) NOT NULL,
    decided_by_id bigint,
    employee_id bigint NOT NULL,
    CONSTRAINT assessment_reattempt_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.assessment_reattempt_requests OWNER TO postgres;

--
-- Name: assessment_reattempt_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessment_reattempt_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_reattempt_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_results (
    result_id bigint NOT NULL,
    improvement integer,
    previous_proficiency character varying(255),
    proficiency character varying(255),
    score double precision,
    assessment_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    CONSTRAINT assessment_results_previous_proficiency_check CHECK (((previous_proficiency)::text = ANY ((ARRAY['UNAWARE'::character varying, 'BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[]))),
    CONSTRAINT assessment_results_proficiency_check CHECK (((proficiency)::text = ANY ((ARRAY['UNAWARE'::character varying, 'BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[])))
);


ALTER TABLE public.assessment_results OWNER TO postgres;

--
-- Name: assessment_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessment_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessments (
    id bigint NOT NULL,
    assessment_type character varying(255) NOT NULL,
    comments character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    date timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    submitted_at timestamp(6) with time zone,
    assessor_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT assessments_assessment_type_check CHECK (((assessment_type)::text = ANY ((ARRAY['SELF'::character varying, 'PEER'::character varying, 'MANAGER'::character varying])::text[]))),
    CONSTRAINT assessments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.assessments OWNER TO postgres;

--
-- Name: assessments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    actor_email character varying(255),
    actor_user_id bigint,
    details character varying(4000),
    entity_id character varying(255),
    entity_type character varying(255),
    ip_address character varying(255),
    "timestamp" timestamp(6) with time zone NOT NULL
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certifications (
    id bigint NOT NULL,
    expires_at date,
    issued_at date NOT NULL,
    issuer character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT certifications_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRING_SOON'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.certifications OWNER TO postgres;

--
-- Name: certifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(3000),
    difficulty character varying(255),
    duration_hours double precision,
    duration_label character varying(255),
    external_url character varying(255),
    is_internal boolean NOT NULL,
    provider character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    skill_id bigint
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_otps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_otps (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    code_hash character varying(255) NOT NULL,
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    purpose character varying(255) NOT NULL,
    CONSTRAINT email_otps_purpose_check CHECK (((purpose)::text = 'SIGNUP_VERIFICATION'::text))
);


ALTER TABLE public.email_otps OWNER TO postgres;

--
-- Name: email_otps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.email_otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_profiles (
    id bigint NOT NULL,
    bio character varying(2000),
    department character varying(255),
    education character varying(4000),
    job_role character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    work_experience character varying(4000),
    user_id bigint NOT NULL
);


ALTER TABLE public.employee_profiles OWNER TO postgres;

--
-- Name: employee_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    completion_date timestamp(6) with time zone,
    last_progress_update_at timestamp(6) with time zone NOT NULL,
    progress double precision NOT NULL,
    start_date timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    target_completion_date timestamp(6) with time zone,
    course_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CERTIFIED'::character varying, 'EXPIRED_RENEWAL'::character varying])::text[])))
);


ALTER TABLE public.enrollments OWNER TO postgres;

--
-- Name: enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gap_analyses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gap_analyses (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    current_score double precision NOT NULL,
    gap_score double precision NOT NULL,
    missing_skill boolean NOT NULL,
    risk_severity character varying(255) NOT NULL,
    target_score double precision NOT NULL,
    skill_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT gap_analyses_risk_severity_check CHECK (((risk_severity)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[])))
);


ALTER TABLE public.gap_analyses OWNER TO postgres;

--
-- Name: gap_analyses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gap_analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gap_analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gap_snapshots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gap_snapshots (
    id bigint NOT NULL,
    avg_gap_score double precision NOT NULL,
    critical_gaps_count integer NOT NULL,
    department character varying(255) NOT NULL,
    high_gaps_count integer NOT NULL,
    low_gaps_count integer NOT NULL,
    medium_gaps_count integer NOT NULL,
    snapshot_date date NOT NULL,
    total_gaps integer NOT NULL
);


ALTER TABLE public.gap_snapshots OWNER TO postgres;

--
-- Name: gap_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gap_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gap_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knowledge_sessions (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(3000),
    duration_minutes integer NOT NULL,
    session_date timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    mentor_id bigint NOT NULL,
    CONSTRAINT knowledge_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.knowledge_sessions OWNER TO postgres;

--
-- Name: knowledge_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.knowledge_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_milestones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_milestones (
    milestone_id bigint NOT NULL,
    completion_percentage double precision NOT NULL,
    sequence_no integer NOT NULL,
    title character varying(255) NOT NULL,
    enrollment_id bigint,
    training_id bigint NOT NULL
);


ALTER TABLE public.learning_milestones OWNER TO postgres;

--
-- Name: learning_milestones_milestone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.learning_milestones ALTER COLUMN milestone_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_milestones_milestone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_path_courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_path_courses (
    id bigint NOT NULL,
    sequence_order integer NOT NULL,
    course_id bigint NOT NULL,
    learning_path_id bigint NOT NULL
);


ALTER TABLE public.learning_path_courses OWNER TO postgres;

--
-- Name: learning_path_courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.learning_path_courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_path_courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_path_steps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_path_steps (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    difficulty_stage character varying(255) NOT NULL,
    estimated_hours integer,
    status character varying(255) NOT NULL,
    step_order integer NOT NULL,
    course_id bigint,
    learning_path_id bigint NOT NULL
);


ALTER TABLE public.learning_path_steps OWNER TO postgres;

--
-- Name: learning_path_steps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.learning_path_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_path_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_paths; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_paths (
    id bigint NOT NULL,
    description character varying(3000),
    generated_at timestamp(6) without time zone,
    no_courses_available boolean NOT NULL,
    overall_progress_percent integer,
    status character varying(255) NOT NULL,
    target_department character varying(255),
    target_role character varying(255),
    target_severity character varying(255),
    title character varying(255) NOT NULL,
    total_estimated_hours integer,
    employee_id bigint,
    target_skill_id bigint
);


ALTER TABLE public.learning_paths OWNER TO postgres;

--
-- Name: learning_paths_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.learning_paths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentorship_matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mentorship_matches (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    end_date date,
    goal character varying(2000),
    start_date date,
    status character varying(255) NOT NULL,
    mentee_id bigint NOT NULL,
    mentor_id bigint NOT NULL,
    target_skill_id bigint NOT NULL,
    CONSTRAINT mentorship_matches_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.mentorship_matches OWNER TO postgres;

--
-- Name: mentorship_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mentorship_matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentorship_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    dedupe_key character varying(255),
    is_read boolean NOT NULL,
    message character varying(3000) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_competencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_competencies (
    id bigint NOT NULL,
    department character varying(255) NOT NULL,
    job_title character varying(255) NOT NULL,
    required_proficiency_level character varying(255) NOT NULL,
    skill_id bigint NOT NULL,
    CONSTRAINT role_competencies_required_proficiency_level_check CHECK (((required_proficiency_level)::text = ANY ((ARRAY['UNAWARE'::character varying, 'BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[])))
);


ALTER TABLE public.role_competencies OWNER TO postgres;

--
-- Name: role_competencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_competencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_competencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_registrations (
    id bigint NOT NULL,
    attendance_status character varying(255) NOT NULL,
    feedback_rating integer,
    feedback_submitted_at timestamp(6) with time zone,
    feedback_text character varying(2000),
    registered_at timestamp(6) with time zone NOT NULL,
    employee_id bigint NOT NULL,
    session_id bigint NOT NULL,
    CONSTRAINT session_registrations_attendance_status_check CHECK (((attendance_status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'ATTENDED'::character varying, 'ABSENT'::character varying])::text[])))
);


ALTER TABLE public.session_registrations OWNER TO postgres;

--
-- Name: session_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skills (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    description character varying(2000),
    name character varying(255) NOT NULL
);


ALTER TABLE public.skills OWNER TO postgres;

--
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_recommendations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.training_recommendations (
    id bigint NOT NULL,
    generated_at timestamp(6) without time zone NOT NULL,
    priority_rank integer NOT NULL,
    recommendation_text character varying(2000) NOT NULL,
    relevance_score double precision NOT NULL,
    score_breakdown character varying(2000),
    source_gap_severity character varying(255) NOT NULL,
    suggested_resource_type character varying(255) NOT NULL,
    employee_id bigint NOT NULL,
    skill_id bigint NOT NULL
);


ALTER TABLE public.training_recommendations OWNER TO postgres;

--
-- Name: training_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.training_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_skills (
    id bigint NOT NULL,
    proficiency_level character varying(255) NOT NULL,
    rating_score double precision NOT NULL,
    skill_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_skills_proficiency_level_check CHECK (((proficiency_level)::text = ANY ((ARRAY['UNAWARE'::character varying, 'BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[])))
);


ALTER TABLE public.user_skills OWNER TO postgres;

--
-- Name: user_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    avatar_url character varying(255),
    department character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    job_title character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    manager_id bigint,
    target_department character varying(255),
    target_job_title character varying(255),
    email_verified boolean,
    access_decided_at timestamp(6) with time zone,
    access_decision_note character varying(1000),
    access_status character varying(255),
    access_decided_by bigint,
    CONSTRAINT users_access_status_check CHECK (((access_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'MANAGER'::character varying, 'DEPARTMENT_HEAD'::character varying, 'HR_SPECIALIST'::character varying, 'HR_ADMIN'::character varying, 'LND_ADMIN'::character varying, 'SYSTEM_ADMIN'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: assessment_questions assessment_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_questions
    ADD CONSTRAINT assessment_questions_pkey PRIMARY KEY (id);


--
-- Name: assessment_reattempt_requests assessment_reattempt_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_reattempt_requests
    ADD CONSTRAINT assessment_reattempt_requests_pkey PRIMARY KEY (id);


--
-- Name: assessment_results assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT assessment_results_pkey PRIMARY KEY (result_id);


--
-- Name: assessments assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT assessments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: certifications certifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certifications
    ADD CONSTRAINT certifications_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: email_otps email_otps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_otps
    ADD CONSTRAINT email_otps_pkey PRIMARY KEY (id);


--
-- Name: employee_profiles employee_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_profiles
    ADD CONSTRAINT employee_profiles_pkey PRIMARY KEY (id);


--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);


--
-- Name: gap_analyses gap_analyses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gap_analyses
    ADD CONSTRAINT gap_analyses_pkey PRIMARY KEY (id);


--
-- Name: gap_snapshots gap_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gap_snapshots
    ADD CONSTRAINT gap_snapshots_pkey PRIMARY KEY (id);


--
-- Name: knowledge_sessions knowledge_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knowledge_sessions
    ADD CONSTRAINT knowledge_sessions_pkey PRIMARY KEY (id);


--
-- Name: learning_milestones learning_milestones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_milestones
    ADD CONSTRAINT learning_milestones_pkey PRIMARY KEY (milestone_id);


--
-- Name: learning_path_courses learning_path_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_courses
    ADD CONSTRAINT learning_path_courses_pkey PRIMARY KEY (id);


--
-- Name: learning_path_steps learning_path_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_steps
    ADD CONSTRAINT learning_path_steps_pkey PRIMARY KEY (id);


--
-- Name: learning_paths learning_paths_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT learning_paths_pkey PRIMARY KEY (id);


--
-- Name: mentorship_matches mentorship_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentorship_matches
    ADD CONSTRAINT mentorship_matches_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_competencies role_competencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_competencies
    ADD CONSTRAINT role_competencies_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: session_registrations session_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_registrations
    ADD CONSTRAINT session_registrations_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: training_recommendations training_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_recommendations
    ADD CONSTRAINT training_recommendations_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: skills uk85woe63nu9klkk9fa73vf0jd0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT uk85woe63nu9klkk9fa73vf0jd0 UNIQUE (name);


--
-- Name: employee_profiles uk8yk3u81veuwf2re5iuf6qxkn9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_profiles
    ADD CONSTRAINT uk8yk3u81veuwf2re5iuf6qxkn9 UNIQUE (user_id);


--
-- Name: role_competencies uk_role_dept_skill; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_competencies
    ADD CONSTRAINT uk_role_dept_skill UNIQUE (job_title, department, skill_id);


--
-- Name: session_registrations uk_session_employee; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_registrations
    ADD CONSTRAINT uk_session_employee UNIQUE (session_id, employee_id);


--
-- Name: user_skills uk_user_skill; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT uk_user_skill UNIQUE (user_id, skill_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_skills user_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_assessment_questions_skill; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_assessment_questions_skill ON public.assessment_questions USING btree (skill_id);


--
-- Name: idx_email_otps_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_email_otps_email ON public.email_otps USING btree (email);


--
-- Name: idx_email_otps_expires_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_email_otps_expires_at ON public.email_otps USING btree (expires_at);


--
-- Name: idx_user_skill_skill_proficiency; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_skill_skill_proficiency ON public.user_skills USING btree (skill_id, proficiency_level);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: learning_milestones fk33tgmnbcl2kf9sndoghacfet1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_milestones
    ADD CONSTRAINT fk33tgmnbcl2kf9sndoghacfet1 FOREIGN KEY (training_id) REFERENCES public.courses(id);


--
-- Name: training_recommendations fk4c66m2bmiai5l6r62teo80lml; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_recommendations
    ADD CONSTRAINT fk4c66m2bmiai5l6r62teo80lml FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: users fk5p1ci5btqfwvtaqx5n2wxi182; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk5p1ci5btqfwvtaqx5n2wxi182 FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- Name: role_competencies fk608yfwjc0rj95trtm45qmuxr7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_competencies
    ADD CONSTRAINT fk608yfwjc0rj95trtm45qmuxr7 FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: learning_path_courses fk61a7mpfalmcy1635rl3ieohu3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_courses
    ADD CONSTRAINT fk61a7mpfalmcy1635rl3ieohu3 FOREIGN KEY (learning_path_id) REFERENCES public.learning_paths(id);


--
-- Name: assessment_questions fk7t9xt5x7b5ocv7mf6lx3bkd5t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_questions
    ADD CONSTRAINT fk7t9xt5x7b5ocv7mf6lx3bkd5t FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: assessments fk8chd5jbuae75ajbhmai0kbesh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT fk8chd5jbuae75ajbhmai0kbesh FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: mentorship_matches fkbiglokti9fbdvj4aru9ete1l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentorship_matches
    ADD CONSTRAINT fkbiglokti9fbdvj4aru9ete1l FOREIGN KEY (mentee_id) REFERENCES public.users(id);


--
-- Name: learning_path_steps fkbq44gpn9511me1ctpp4cht62m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_steps
    ADD CONSTRAINT fkbq44gpn9511me1ctpp4cht62m FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: learning_path_courses fkc3s7jkivrrx2ngi7xyro311mg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_courses
    ADD CONSTRAINT fkc3s7jkivrrx2ngi7xyro311mg FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: learning_paths fkc92umimbbus6vrsp9gryojyen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkc92umimbbus6vrsp9gryojyen FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: training_recommendations fkcdx2rn2mlxnvafwy78p399cg6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_recommendations
    ADD CONSTRAINT fkcdx2rn2mlxnvafwy78p399cg6 FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: employee_profiles fkeotvdthm6gd1pavuhb075uocm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_profiles
    ADD CONSTRAINT fkeotvdthm6gd1pavuhb075uocm FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: mentorship_matches fkg6un4t7dkw9akc02708h9dwpk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentorship_matches
    ADD CONSTRAINT fkg6un4t7dkw9akc02708h9dwpk FOREIGN KEY (target_skill_id) REFERENCES public.skills(id);


--
-- Name: users fkgnibx9hwkww60lcp6x639y40r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkgnibx9hwkww60lcp6x639y40r FOREIGN KEY (access_decided_by) REFERENCES public.users(id);


--
-- Name: user_skills fkh223y61gwijpgqt6nlsuti07g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT fkh223y61gwijpgqt6nlsuti07g FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: enrollments fkho8mcicp4196ebpltdn9wl6co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkho8mcicp4196ebpltdn9wl6co FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: knowledge_sessions fkhqsfp1a0qnfrt6i4nox0ekli7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knowledge_sessions
    ADD CONSTRAINT fkhqsfp1a0qnfrt6i4nox0ekli7 FOREIGN KEY (mentor_id) REFERENCES public.users(id);


--
-- Name: achievements fkhrpasex6kx690kyhbbp503sh6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT fkhrpasex6kx690kyhbbp503sh6 FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: assessment_reattempt_requests fkhv39efndbyxp6wlhq9bu5t9yr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_reattempt_requests
    ADD CONSTRAINT fkhv39efndbyxp6wlhq9bu5t9yr FOREIGN KEY (decided_by_id) REFERENCES public.users(id);


--
-- Name: learning_path_steps fkjyfnrb9kdlkcps2k3tkc56x6d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_path_steps
    ADD CONSTRAINT fkjyfnrb9kdlkcps2k3tkc56x6d FOREIGN KEY (learning_path_id) REFERENCES public.learning_paths(id);


--
-- Name: assessments fkkb20rpt9vs8ryrra0ktcjfl56; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT fkkb20rpt9vs8ryrra0ktcjfl56 FOREIGN KEY (assessor_id) REFERENCES public.users(id);


--
-- Name: session_registrations fkmcj3fy4dtxlv441tkx3pn2vr0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_registrations
    ADD CONSTRAINT fkmcj3fy4dtxlv441tkx3pn2vr0 FOREIGN KEY (session_id) REFERENCES public.knowledge_sessions(id);


--
-- Name: assessment_results fkmfmtvlljdarrrr5ad8tnwqkn8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fkmfmtvlljdarrrr5ad8tnwqkn8 FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: enrollments fkn428p876eg5maqq1m60avgdn4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkn428p876eg5maqq1m60avgdn4 FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: assessment_reattempt_requests fknjrtgkquhqon5qbtft9wtdbk6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_reattempt_requests
    ADD CONSTRAINT fknjrtgkquhqon5qbtft9wtdbk6 FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: learning_milestones fkobec1x8ywjffddoeohwupa7d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_milestones
    ADD CONSTRAINT fkobec1x8ywjffddoeohwupa7d FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id);


--
-- Name: assessment_results fkp1ml4sw7ygau1bm5hhcpo2hhu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fkp1ml4sw7ygau1bm5hhcpo2hhu FOREIGN KEY (assessment_id) REFERENCES public.assessments(id);


--
-- Name: certifications fkq2rtmrlc1g36q3eva026779x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certifications
    ADD CONSTRAINT fkq2rtmrlc1g36q3eva026779x FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: mentorship_matches fkq8xmswmc8dst39dxi6p4kgdad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentorship_matches
    ADD CONSTRAINT fkq8xmswmc8dst39dxi6p4kgdad FOREIGN KEY (mentor_id) REFERENCES public.users(id);


--
-- Name: learning_paths fkqbug7w67ipsu0ffc3tgluff8k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkqbug7w67ipsu0ffc3tgluff8k FOREIGN KEY (target_skill_id) REFERENCES public.skills(id);


--
-- Name: session_registrations fkqnuwg647al6grpg3mpsxkxemg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_registrations
    ADD CONSTRAINT fkqnuwg647al6grpg3mpsxkxemg FOREIGN KEY (employee_id) REFERENCES public.users(id);


--
-- Name: courses fkqpfl9aa3l7ty4ov1ibclumu9m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fkqpfl9aa3l7ty4ov1ibclumu9m FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- Name: user_skills fkro13if9r7fwkr5115715127ai; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT fkro13if9r7fwkr5115715127ai FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: gap_analyses fkrv486utc3p13amkj3v214dfbq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gap_analyses
    ADD CONSTRAINT fkrv486utc3p13amkj3v214dfbq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: gap_analyses fktcaowwufdt076tosw2j8htbb5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gap_analyses
    ADD CONSTRAINT fktcaowwufdt076tosw2j8htbb5 FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- PostgreSQL database dump complete
--

\unrestrict c5Sje78CGcDUu7Xujd9Gab5x7XbIxYnkoj2idrmAfceXEEPl6FIDbh7qof79W30

