package com.okip.service.preferences;
import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.okip.dto.preferences.EmployeePreferencesDTO; import com.okip.entity.master.Employee; import com.okip.entity.master.EmployeePreferences; import com.okip.entity.master.EmployeePreferences.ProfileVisibility; import com.okip.entity.master.EmployeePreferences.Theme; import com.okip.exception.ResourceNotFoundException; import com.okip.repository.EmployeePreferencesRepository; import com.okip.repository.EmployeeRepository;
@Service @Transactional public class PreferencesServiceImpl implements PreferencesService{
 private final EmployeePreferencesRepository repo; private final EmployeeRepository employees; public PreferencesServiceImpl(EmployeePreferencesRepository r,EmployeeRepository e){repo=r;employees=e;}
 @Override public EmployeePreferencesDTO getMine(){return toDto(getOrCreate());}
 @Override public EmployeePreferencesDTO update(EmployeePreferencesDTO d){EmployeePreferences p=getOrCreate(); if(d==null) throw new IllegalArgumentException("Preferences cannot be null."); p.setEmailNotifications(d.emailNotifications);p.setPushNotifications(d.pushNotifications);p.setLearningReminders(d.learningReminders);p.setSkillGapAlerts(d.skillGapAlerts);p.setTrainingNotifications(d.trainingNotifications);p.setAssessmentReminders(d.assessmentReminders);p.setCertificateUpdates(d.certificateUpdates); try{p.setProfileVisibility(ProfileVisibility.valueOf(d.profileVisibility));}catch(Exception ignored){} try{p.setTheme(Theme.valueOf(d.theme));}catch(Exception ignored){} return toDto(repo.save(p)); }
 private EmployeePreferences getOrCreate(){String email=SecurityContextHolder.getContext().getAuthentication().getName(); Employee e=employees.findByOfficialEmail(email).orElseThrow(()->new ResourceNotFoundException("Employee not found.")); return repo.findByEmployee(e).orElseGet(()->{EmployeePreferences p=new EmployeePreferences();p.setEmployee(e);return repo.save(p);});}
 private EmployeePreferencesDTO toDto(EmployeePreferences p){EmployeePreferencesDTO d=new EmployeePreferencesDTO();d.emailNotifications=p.isEmailNotifications();d.pushNotifications=p.isPushNotifications();d.learningReminders=p.isLearningReminders();d.skillGapAlerts=p.isSkillGapAlerts();d.trainingNotifications=p.isTrainingNotifications();d.assessmentReminders=p.isAssessmentReminders();d.certificateUpdates=p.isCertificateUpdates();d.profileVisibility=p.getProfileVisibility().name();d.theme=p.getTheme().name();return d;}
}
