package com.orgskills.intelligence.entity.enums;

public enum NotificationType {
    GAP_ALERT,
    TRAINING_DEADLINE,
    MENTORSHIP_INVITE,
    SESSION_REMINDER,
    ASSESSMENT_REMINDER,
    TRAINING_RECOMMENDATION,
    TRAINING_PROGRESS,
    ACHIEVEMENT_UNLOCKED,
    ASSESSMENT_RESULT,
    MENTORSHIP_REQUEST,
    INFO,
    SYSTEM_ALERT
}
