import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { initDB, query, isPostgresConnected, memoryStore } from './db.js';

dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors());
app.use(express.json());
initDB();

const ROLE_BENCHMARKS={"Software Developer":[['Java','Programming','Advanced',85],['Spring Boot','Framework','Intermediate',60],['System Design','Architecture','Advanced',85],['Microservices','Architecture','Advanced',85],['Docker','DevOps','Intermediate',60],['AWS','DevOps','Intermediate',60],['Kubernetes','DevOps','Advanced',85]]};
const severity=(r,c)=>{const d=Math.max(0,r-c); return d>=40?'Critical':d>=20?'Moderate':d>0?'Minor':'Met';};
const ok=(res,data)=>res.json({success:true,data});
const fail=(res,e)=>res.status(500).json({success:false,error:e.message});

app.get('/api/status',(req,res)=>res.json({status:'Online',database:isPostgresConnected?'PostgreSQL Active':'In-memory fallback',timestamp:new Date().toISOString()}));
app.get('/api/courses',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query('SELECT * FROM courses ORDER BY rating DESC,id')).rows); return ok(res,memoryStore.courses)}catch(e){fail(res,e)}});

async function calculateGap(userId,targetRole){
 let skills=isPostgresConnected?(await query('SELECT * FROM user_skills WHERE user_id=$1',[userId])).rows:memoryStore.userSkills.filter(x=>x.user_id==userId);
 let reqs=isPostgresConnected?(await query('SELECT * FROM role_requirements WHERE role_name=$1 ORDER BY id',[targetRole])).rows:[];
 if(!reqs.length)(ROLE_BENCHMARKS[targetRole]||ROLE_BENCHMARKS['Software Developer']).forEach(x=>reqs.push({skill_name:x[0],category:x[1],required_level:x[2],required_score:x[3]}));
 const details=reqs.map(r=>{const s=skills.find(x=>x.skill_name.toLowerCase()===r.skill_name.toLowerCase());const current=s?.score??30;const level=severity(r.required_score,current);return {skill:r.skill_name,category:r.category,required:r.required_level,requiredScore:r.required_score,current:s?.proficiency_level||'Beginner',currentScore:current,level,class:level.toLowerCase(),gapScore:Math.max(0,r.required_score-current)}});
 const totalR=details.reduce((a,x)=>a+x.requiredScore,0), totalC=details.reduce((a,x)=>a+x.currentScore,0); const counts={Critical:0,Moderate:0,Minor:0}; details.forEach(x=>{if(counts[x.level]!=null)counts[x.level]++});
 return {userId,targetRole,criticalCount:counts.Critical,moderateCount:counts.Moderate,minorCount:counts.Minor,readinessScore:Math.round(totalC/(totalR||1)*100),gapDetails:details,timestamp:new Date().toISOString()};
}
app.post('/api/gap-analysis/calculate',async(req,res)=>{try{const {userId=1,targetRole='Software Developer'}=req.body;const data=await calculateGap(userId,targetRole);if(isPostgresConnected)await query('INSERT INTO gap_analysis_results(user_id,target_role,critical_gaps_count,moderate_gaps_count,minor_gaps_count,gap_details) VALUES($1,$2,$3,$4,$5,$6)',[userId,targetRole,data.criticalCount,data.moderateCount,data.minorCount,JSON.stringify(data.gapDetails)]);ok(res,data)}catch(e){fail(res,e)}});
app.get('/api/gap-analysis/:userId',async(req,res)=>{try{ok(res,await calculateGap(req.params.userId,req.query.role||'Software Developer'))}catch(e){fail(res,e)}});
app.post('/api/ai/recommendations',async(req,res)=>{const gaps=req.body.gaps||[];ok(res,{summary:`Prioritize ${gaps.filter(x=>x.level==='Critical').length||gaps.length} high-impact skill gaps for the selected role.`,priorityActions:gaps.slice(0,3).map(x=>`Build ${x.skill} through a structured course, hands-on project and mentor review.`),recommendedTrack:'Cloud Native & Microservices Upskilling Path',estimatedWeeks:6})});
app.get('/api/learning-paths/:userId',async(req,res)=>{try{if(isPostgresConnected){let r=await query('SELECT * FROM learning_paths WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.params.userId]);if(!r.rows.length){const g=await calculateGap(req.params.userId,'Software Developer');const gaps=g.gapDetails.filter(x=>x.level!=='Met').sort((a,b)=>b.gapScore-a.gapScore);const steps=gaps.map((x,i)=>({stage:i+1,skill:x.skill,severity:x.level,estimatedHours:Math.max(5,Math.round(x.gapScore/2)),courses:[]}));await query('INSERT INTO learning_paths(user_id,path_name,target_role,total_hours,estimated_weeks,steps) VALUES($1,$2,$3,$4,$5,$6)',[req.params.userId,'Personalized Software Developer Upskilling Path','Software Developer',steps.reduce((a,x)=>a+x.estimatedHours,0),6,JSON.stringify(steps)]);r=await query('SELECT * FROM learning_paths WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.params.userId]);}const p=r.rows[0];return ok(res,{id:p.id,title:p.path_name,targetRole:p.target_role,totalDuration:`${p.total_hours} Hours`,estimatedTime:`${p.estimated_weeks} Weeks`,stages:p.steps});}return ok(res,{title:'Full Stack Architect & Cloud Engineer Pathway',targetRole:'Software Developer',totalDuration:'75 Hours',estimatedTime:'6 Weeks',stages:[]})}catch(e){fail(res,e)}});

app.get('/api/learning/:userId',async(req,res)=>{try{if(isPostgresConnected){return ok(res,(await query(`SELECT e.*,c.title,c.provider,c.skill_name,c.duration FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 ORDER BY e.enrolled_at DESC`,[req.params.userId])).rows)}return ok(res,[])}catch(e){fail(res,e)}});
app.post('/api/learning/enroll',async(req,res)=>{try{const {userId=1,courseId}=req.body;if(!courseId)return res.status(400).json({success:false,error:'courseId is required'});if(isPostgresConnected){const r=await query(`INSERT INTO enrollments(user_id,course_id) VALUES($1,$2) ON CONFLICT(user_id,course_id) DO UPDATE SET status='In Progress',started_at=COALESCE(enrollments.started_at,CURRENT_TIMESTAMP) RETURNING *`,[userId,courseId]);await query(`INSERT INTO notifications(user_id,title,message,type) VALUES($1,'Training enrolled','You are enrolled in a new learning course.','TRAINING')`,[userId]);return ok(res,r.rows[0])}ok(res,{user_id:userId,course_id:courseId,status:'In Progress',progress:0})}catch(e){fail(res,e)}});
app.patch('/api/learning/:id/progress',async(req,res)=>{try{const p=Math.max(0,Math.min(100,Number(req.body.progress)));const status=p===100?'Completed':'In Progress';if(isPostgresConnected){const r=await query(`UPDATE enrollments SET progress=$1,status=$2,completed_modules=ROUND(total_modules*$1/100.0),started_at=COALESCE(started_at,CURRENT_TIMESTAMP),completed_at=CASE WHEN $1=100 THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE id=$3 RETURNING *`,[p,status,req.params.id]);if(!r.rows.length)return res.status(404).json({success:false,error:'Enrollment not found'});return ok(res,r.rows[0])}ok(res,{id:req.params.id,progress:p,status})}catch(e){fail(res,e)}});

app.get('/api/mentors',async(req,res)=>{try{if(isPostgresConnected){const r=await query(`SELECT m.*,u.name,u.email,u.role FROM mentors m JOIN users u ON u.id=m.user_id ORDER BY m.rating DESC`);return ok(res,r.rows.map(m=>({...m,expertise:m.expertise||[],wants_to_learn:m.wants_to_learn||[]})))}ok(res,[])}catch(e){fail(res,e)}});
app.get('/api/sessions',async(req,res)=>{try{if(isPostgresConnected){const r=await query(`SELECT s.*,u.name AS host,COUNT(a.id)::int AS attendees FROM knowledge_sessions s JOIN mentors m ON m.id=s.mentor_id JOIN users u ON u.id=m.user_id LEFT JOIN session_attendees a ON a.session_id=s.id GROUP BY s.id,u.name ORDER BY s.session_date`);return ok(res,r.rows)}ok(res,[])}catch(e){fail(res,e)}});
app.post('/api/sessions',async(req,res)=>{try{const {mentorId,topic,description='',sessionDate,durationMinutes=60,capacity=20,meetingUrl=''}=req.body;if(!mentorId||!topic||!sessionDate)return res.status(400).json({success:false,error:'mentorId, topic and sessionDate are required'});if(isPostgresConnected){const r=await query(`INSERT INTO knowledge_sessions(mentor_id,topic,description,session_date,duration_minutes,capacity,meeting_url) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[mentorId,topic,description,sessionDate,durationMinutes,capacity,meetingUrl]);return ok(res,r.rows[0])}ok(res,req.body)}catch(e){fail(res,e)}});
app.post('/api/sessions/:id/rsvp',async(req,res)=>{try{const userId=req.body.userId||1;if(isPostgresConnected){const s=await query('SELECT capacity FROM knowledge_sessions WHERE id=$1',[req.params.id]);if(!s.rows.length)return res.status(404).json({success:false,error:'Session not found'});const c=await query(`SELECT COUNT(*)::int AS n FROM session_attendees WHERE session_id=$1`,[req.params.id]);if(c.rows[0].n>=s.rows[0].capacity)return res.status(409).json({success:false,error:'Session is full'});const r=await query(`INSERT INTO session_attendees(session_id,user_id) VALUES($1,$2) ON CONFLICT(session_id,user_id) DO UPDATE SET status='Registered' RETURNING *`,[req.params.id,userId]);await query(`INSERT INTO notifications(user_id,title,message,type) VALUES($1,'Mentorship RSVP confirmed','Your knowledge-sharing session registration is confirmed.','MENTORSHIP')`,[userId]);return ok(res,r.rows[0])}ok(res,{session_id:req.params.id,user_id:userId,status:'Registered'})}catch(e){fail(res,e)}});

app.get('/api/assessments/:userId',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query(`SELECT a.*,u.name AS subject_name FROM assessments a LEFT JOIN users u ON u.id=a.subject_user_id WHERE a.subject_user_id=$1 OR a.assessor_user_id=$1 ORDER BY CASE WHEN a.status='Pending' THEN 0 ELSE 1 END,a.due_date NULLS LAST`,[req.params.userId])).rows);return ok(res,[])}catch(e){fail(res,e)}});
app.post('/api/assessments/:id/submit',async(req,res)=>{try{const answers=req.body.answers||[];if(!answers.length)return res.status(400).json({success:false,error:'answers are required'});const score=Math.round(answers.reduce((a,x)=>a+Number(x.score||0),0)/answers.length);if(isPostgresConnected){await query('BEGIN');try{for(const a of answers)await query(`INSERT INTO assessment_responses(assessment_id,question_no,score) VALUES($1,$2,$3) ON CONFLICT(assessment_id,question_no) DO UPDATE SET score=EXCLUDED.score`,[req.params.id,a.questionNo,a.score]);const ar=await query(`UPDATE assessments SET status='Completed',score=$1,completed_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *`,[score,req.params.id]);if(!ar.rows.length){await query('ROLLBACK');return res.status(404).json({success:false,error:'Assessment not found'})}const a=ar.rows[0];if(a.subject_user_id&&a.skill_name){const level=score>=85?'Advanced':score>=60?'Intermediate':'Beginner';await query(`INSERT INTO user_skills(user_id,skill_name,category,proficiency_level,score) VALUES($1,$2,'Assessed','${level}',$3) ON CONFLICT(user_id,skill_name) DO UPDATE SET score=EXCLUDED.score,proficiency_level=EXCLUDED.proficiency_level,updated_at=CURRENT_TIMESTAMP`,[a.subject_user_id,a.skill_name,score]);await query(`INSERT INTO notifications(user_id,title,message,type) VALUES($1,'Assessment completed','Your assessment score was updated and skill-gap analysis can be recalculated.','ASSESSMENT')`,[a.subject_user_id]);}await query('COMMIT');return ok(res,{assessment:a,score})}catch(e){await query('ROLLBACK');throw e}}ok(res,{id:req.params.id,status:'Completed',score})}catch(e){fail(res,e)}});

app.get('/api/notifications/:userId',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC',[req.params.userId])).rows);return ok(res,[])}catch(e){fail(res,e)}});
app.patch('/api/notifications/:id/read',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *',[req.params.id])).rows[0]);ok(res,{id:req.params.id,read_at:new Date().toISOString()})}catch(e){fail(res,e)}});
app.post('/api/notifications/:userId/read-all',async(req,res)=>{try{if(isPostgresConnected)await query('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND read_at IS NULL',[req.params.userId]);ok(res,{updated:true})}catch(e){fail(res,e)}});

app.post('/api/sessions/:id/feedback',async(req,res)=>{try{const {userId=1,rating,comment=''}=req.body;if(!rating||rating<1||rating>5)return res.status(400).json({success:false,error:'rating must be 1-5'});if(isPostgresConnected){const r=await query(`INSERT INTO session_feedback(session_id,user_id,rating,comment) VALUES($1,$2,$3,$4) ON CONFLICT(session_id,user_id) DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment RETURNING *`,[req.params.id,userId,rating,comment]);return ok(res,r.rows[0])}ok(res,{session_id:req.params.id,user_id:userId,rating,comment})}catch(e){fail(res,e)}});
app.get('/api/resources',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query(`SELECT r.*,u.name AS author_name FROM knowledge_resources r LEFT JOIN users u ON u.id=r.author_user_id ORDER BY r.created_at DESC`)).rows);ok(res,[])}catch(e){fail(res,e)}});
app.get('/api/communities',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query(`SELECT c.*,COUNT(cm.id)::int AS members FROM communities c LEFT JOIN community_members cm ON cm.community_id=c.id GROUP BY c.id ORDER BY c.name`)).rows);ok(res,[])}catch(e){fail(res,e)}});
app.post('/api/communities/:id/join',async(req,res)=>{try{const userId=req.body.userId||1;if(isPostgresConnected){const r=await query(`INSERT INTO community_members(community_id,user_id) VALUES($1,$2) ON CONFLICT(community_id,user_id) DO NOTHING RETURNING *`,[req.params.id,userId]);return ok(res,r.rows[0]||{community_id:req.params.id,user_id:userId})}ok(res,{community_id:req.params.id,user_id:userId})}catch(e){fail(res,e)}});
app.get('/api/learning/renewals/:userId',async(req,res)=>{try{if(isPostgresConnected)return ok(res,(await query(`SELECT e.*,c.title,c.provider FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 AND e.certification_expiry IS NOT NULL ORDER BY e.certification_expiry`,[req.params.userId])).rows);ok(res,[])}catch(e){fail(res,e)}});

app.get('/api/analytics/:userId',async(req,res)=>{try{const uid=req.params.userId;if(!isPostgresConnected)return ok(res,{enrolledCourses:0,completedCourses:0,averageProgress:0,averageAssessmentScore:0,criticalGaps:0,moderateGaps:0,minorGaps:0});const e=(await query(`SELECT COUNT(*)::int enrolled,COUNT(*) FILTER(WHERE status='Completed')::int completed,COALESCE(AVG(progress),0)::numeric avg_progress FROM enrollments WHERE user_id=$1`,[uid])).rows[0];const a=(await query(`SELECT COALESCE(AVG(score),0)::numeric avg_score FROM assessments WHERE subject_user_id=$1 AND status='Completed'`,[uid])).rows[0];const g=await calculateGap(uid,'Software Developer');ok(res,{enrolledCourses:e.enrolled,completedCourses:e.completed,averageProgress:Number(e.avg_progress).toFixed(1),averageAssessmentScore:Number(a.avg_score).toFixed(1),criticalGaps:g.criticalCount,moderateGaps:g.moderateCount,minorGaps:g.minorCount,readinessScore:g.readinessScore})}catch(e){fail(res,e)}});
app.get('/api/reports/:type/:userId',async(req,res)=>{try{const type=req.params.type,uid=req.params.userId;let rows=[];if(type==='learning'&&isPostgresConnected)rows=(await query(`SELECT c.title,c.provider,c.skill_name,e.status,e.progress,e.enrolled_at,e.completed_at FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 ORDER BY e.enrolled_at DESC`,[uid])).rows;else if(type==='assessments'&&isPostgresConnected)rows=(await query(`SELECT title,type,category,status,score,due_date,completed_at FROM assessments WHERE subject_user_id=$1 ORDER BY created_at DESC`,[uid])).rows;else {const g=await calculateGap(uid,'Software Developer');rows=g.gapDetails;}ok(res,rows)}catch(e){fail(res,e)}});

app.listen(PORT,()=>console.log(`🚀 Knowledge Gap API running on port ${PORT}`));
