package com.okip.service.achievement;
import java.time.LocalDate; import java.util.*; import java.util.stream.Collectors; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.okip.dto.achievement.AchievementDTO; import com.okip.entity.master.Employee; import com.okip.entity.transaction.EmployeeSkill; import com.okip.entity.transaction.EmployeeTraining; import com.okip.exception.ResourceNotFoundException; import com.okip.repository.EmployeeRepository; import com.okip.repository.EmployeeSkillRepository; import com.okip.repository.EmployeeTrainingRepository; import com.okip.repository.EmployeeTrainingModuleProgressRepository; import com.okip.enums.ProficiencyLevel;
@Service @Transactional(readOnly=true) public class AchievementServiceImpl implements AchievementService{
 private final EmployeeRepository employees; private final EmployeeTrainingRepository trainings; private final EmployeeTrainingModuleProgressRepository modules; private final EmployeeSkillRepository skills;
 public AchievementServiceImpl(EmployeeRepository e,EmployeeTrainingRepository t,EmployeeTrainingModuleProgressRepository m,EmployeeSkillRepository s){employees=e;trainings=t;modules=m;skills=s;}
 @Override public List<AchievementDTO> getMine(){Employee e=current();List<EmployeeTraining> ts=trainings.findByEmployeeEmployeeIdOrderByEnrolledAtDesc(e.getEmployeeId());int completed=(int)ts.stream().filter(x->x.getStatus()==EmployeeTraining.Status.COMPLETED).count();int activity=(int)modules.findAll().stream().filter(x->x.getEmployeeTraining()!=null&&x.getEmployeeTraining().getEmployee().getEmployeeId().equals(e.getEmployeeId())&&x.isCompleted()).count();boolean master=skills.findByEmployee(e).stream().map(EmployeeSkill::getProficiencyLevel).anyMatch(p->p==ProficiencyLevel.ADVANCED||p==ProficiencyLevel.EXPERT);Set<LocalDate> dates=ts.stream().map(EmployeeTraining::getLastActivityAt).filter(Objects::nonNull).map(x->x.toLocalDate()).collect(Collectors.toSet());boolean streak=hasSevenDayStreak(dates);return Arrays.asList(item("QUICK_LEARNER","Quick Learner","Completed 5 courses",completed>=5,completed+" completed courses"),item("SKILL_MASTER","Skill Master","Reached Advanced/Expert proficiency",master,master?"Advanced/Expert skill":"No Advanced/Expert skill yet"),item("CONSISTENT_LEARNER","Consistent Learner","7 consecutive learning days",streak,streak?"7-day streak":"7-day streak not reached"),item("KNOWLEDGE_SEEKER","Knowledge Seeker","Completed 10 learning modules",activity>=10,activity+" completed modules"));}
 private boolean hasSevenDayStreak(Set<LocalDate>d){for(LocalDate end:d){boolean ok=true;for(int i=0;i<7;i++)if(!d.contains(end.minusDays(i))){ok=false;break;}if(ok)return true;}return false;}
 private AchievementDTO item(String c,String t,String desc,boolean u,String metric){AchievementDTO a=new AchievementDTO();a.code=c;a.title=t;a.description=desc;a.unlocked=u;a.metric=metric;return a;}
 private Employee current(){String email=SecurityContextHolder.getContext().getAuthentication().getName();return employees.findByOfficialEmail(email).orElseThrow(()->new ResourceNotFoundException("Employee not found."));}
}
