import React,{useEffect,useState} from 'react';
import Sidebar from '../../components/Sidebar/Sidebar'; import Navbar from '../../components/Navbar/Navbar';
import {FaHandsHelping,FaUserFriends,FaCalendarAlt,FaStar,FaSearch,FaPlus,FaComments} from 'react-icons/fa';
import {mentorshipAPI,knowledgeAPI} from '../../services/apiService'; import './KnowledgeSharing.css';
export default function KnowledgeSharing(){
 const[tab,setTab]=useState('mentors'),[mentors,setMentors]=useState([]),[sessions,setSessions]=useState([]),[resources,setResources]=useState([]),[communities,setCommunities]=useState([]),[q,setQ]=useState('');
 const load=async()=>{const[a,b,c,d]=await Promise.all([mentorshipAPI.mentors(),mentorshipAPI.sessions(),knowledgeAPI.resources(),knowledgeAPI.communities()]);if(a.success)setMentors(a.data);if(b.success)setSessions(b.data);if(c.success)setResources(c.data);if(d.success)setCommunities(d.data)}; useEffect(()=>{load()},[]);
 const host=async()=>{const topic=prompt('Knowledge-sharing topic:');if(!topic)return;const date=prompt('Session date/time (YYYY-MM-DDTHH:MM):');if(!date)return;if(!mentors[0])return alert('No mentor/host is available.');await mentorshipAPI.createSession({mentorId:mentors[0].id,topic,sessionDate:date});await load();alert('Session created.')};
 const filtered=mentors.filter(m=>(m.name+' '+(m.expertise||[]).join(' ')).toLowerCase().includes(q.toLowerCase()));
 return <div className="app-layout"><Sidebar/><div className="main-wrapper"><Navbar title="Knowledge Sharing & Mentorship" role="Employee" userName="Bingi Prashanthi"/><div className="page-container">
 <div className="page-header"><div className="page-header-text"><h2><FaHandsHelping/> Peer Mentorship & Knowledge Sharing</h2><p>Expert matching, scheduled sessions, communities and curated learning resources.</p></div><button className="btn btn-primary" onClick={host}><FaPlus/> Host Session</button></div>
 <div className="assessment-tabs"><button className={`tab-btn ${tab==='mentors'?'active':''}`} onClick={()=>setTab('mentors')}><FaUserFriends/> Experts ({mentors.length})</button><button className={`tab-btn ${tab==='sessions'?'active':''}`} onClick={()=>setTab('sessions')}><FaCalendarAlt/> Sessions ({sessions.length})</button><button className={`tab-btn ${tab==='resources'?'active':''}`} onClick={()=>setTab('resources')}>📚 Resources ({resources.length})</button><button className={`tab-btn ${tab==='communities'?'active':''}`} onClick={()=>setTab('communities')}>👥 Communities ({communities.length})</button></div>
 {tab==='mentors'&&<><div className="filter-bar"><div className="navbar-search"><FaSearch/><input placeholder="Search expert or skill..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="mentors-grid">{filtered.map(m=><div key={m.id} className="card-box mentor-card"><div className="mentor-card-top"><div className="mentor-avatar">{m.name?.charAt(0)}</div><div className="mentor-header-info"><h3>{m.name}</h3><p>{m.role}</p><span className="dept">{m.department}</span></div></div><div className="skills-exchange"><div className="exchange-col"><label>Expert in</label><div className="tag-cloud">{(m.expertise||[]).map(s=><span className="badge-pill green" key={s}>{s}</span>)}</div></div><div className="exchange-col"><label>Learning</label><div className="tag-cloud">{(m.wants_to_learn||[]).map(s=><span className="badge-pill blue" key={s}>{s}</span>)}</div></div></div><div className="mentor-card-footer"><span><FaStar/> {m.rating} • {m.sessions_count} sessions</span><button className="btn btn-primary btn-sm" onClick={()=>alert('Connection request sent to '+m.name)}><FaComments/> Connect</button></div></div>)}</div></>}
 {tab==='sessions'&&<div className="sessions-list">{sessions.map(s=><div key={s.id} className="card-box session-card"><div className="session-icon"><FaCalendarAlt/></div><div className="session-details"><span className="badge-pill purple">{s.status}</span><h3>{s.topic}</h3><p>Hosted by <strong>{s.host}</strong> • {new Date(s.session_date).toLocaleString()}</p><span className="attendee-count"><FaUserFriends/> {s.attendees}/{s.capacity} registered</span></div><button className="btn btn-outline" onClick={async()=>{await mentorshipAPI.rsvp(s.id,1);await load();alert('RSVP confirmed.')}}>RSVP / Join</button></div>)}</div>}
 {tab==='resources'&&<div className="reports-grid">{resources.map(r=><div key={r.id} className="card-box report-card"><span className="badge-pill purple">{r.resource_type}</span><h3>{r.title}</h3><p>{r.description}</p><p><strong>{r.skill_name}</strong> • {r.author_name||'Internal'}</p><a className="btn btn-primary btn-sm" href={r.url} target="_blank" rel="noreferrer">Open Resource</a></div>)}</div>}
 {tab==='communities'&&<div className="reports-grid">{communities.map(c=><div key={c.id} className="card-box report-card"><h3>{c.name}</h3><p>{c.description}</p><p>👥 {c.members} members</p><button className="btn btn-primary btn-sm" onClick={async()=>{await knowledgeAPI.joinCommunity(c.id,1);await load();alert('Joined community.')}}>Join Community</button></div>)}</div>}
 </div></div></div>
}
