import { useEffect, useState } from 'react';
import { BookOpen, CheckCircle2, ExternalLink, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { get, post, endpoints, getApiErrorMessage } from '../api';
import { Badge, Button, Card, Empty, ErrorBox, Loading } from '../components/ui';

export default function AI() {
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [busy, setBusy] = useState(false);
  const [enrollingId, setEnrollingId] = useState<number | null>(null);

  async function load() {
    setBusy(true);
    setError('');
    setSuccess('');
    try {
      const res = await post(`${endpoints.ai}/recommendation/my`);
      setData(res);
    } catch (e: any) {
      setError(
        getApiErrorMessage(
          e,
          'AI recommendation is currently unavailable. Ensure your job role and skills are configured.',
        ),
      );
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function handleEnroll(trainingId: number, name: string) {
    setEnrollingId(trainingId);
    setError('');
    setSuccess('');
    try {
      await post(endpoints.enrollments, { trainingId });
      setSuccess(`Enrolled in "${name}"! View progress in My Learning.`);
    } catch (e: any) {
      setError(getApiErrorMessage(e, 'Enrollment failed.'));
    } finally {
      setEnrollingId(null);
    }
  }

  if (busy && !data) return <Loading />;

  const priorityGaps = data?.priorityGaps || [];
  const learningPath = data?.learningPath || [];
  const recommendedCourses = data?.recommendedCourses || [];

  return (
    <>
      <div className="heroRow">
        <div>
          <p className="eyebrow">Spring AI & Gemini Intelligence</p>
          <h2>Personalized AI Learning Roadmap</h2>
          <p className="muted">
            {data?.employeeName ? `Roadmap for ${data.employeeName}` : 'Customized workforce roadmap'} · Generated by analyzing your specific knowledge gaps and career goals.
          </p>
        </div>
        <Button onClick={load} disabled={busy}>
          <Sparkles size={16} style={{ marginRight: 6 }} /> {busy ? 'Generating…' : 'Regenerate Recommendations'}
        </Button>
      </div>

      {error && <ErrorBox message={error} />}
      {success && <div className="successBox">{success}</div>}

      {localStorage.getItem('okip_career_target_role') && (
        <div style={{ background: '#f5f4fb', border: '1px solid #dcd5f7', padding: '12px 16px', borderRadius: 12, marginBottom: 18, display: 'flex', alignItems: 'center', gap: 10 }}>
          <Sparkles size={18} style={{ color: '#5847d6', flexShrink: 0 }} />
          <span style={{ fontSize: '0.88rem', color: '#3b2ca8' }}>
            Aspirational Career Target: <b>{localStorage.getItem('okip_career_target_role')}</b> — Roadmap aligns assigned job role benchmarks with your career growth direction.
          </span>
        </div>
      )}

      <div className="grid2">
        <Card>
          <div className="sectionHead">
            <div>
              <h3>Prioritized Competency Gaps</h3>
              <p className="muted">Ranked by business impact and proficiency discrepancy.</p>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {priorityGaps.map((x: any, i: number) => (
              <div
                key={i}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '12px 16px',
                  borderRadius: 12,
                  border: '1px solid var(--border)',
                  background: '#fcfbfe',
                }}
              >
                <div>
                  <b style={{ fontSize: '1rem' }}>{x.skillName}</b>
                  <p className="muted" style={{ margin: '2px 0 0', fontSize: '0.8rem' }}>
                    {x.gapType ? x.gapType.replace('_', ' ') : 'Skill Gap'}
                  </p>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <Badge tone={String(x.priority).toLowerCase() === 'high' ? 'red' : 'orange'}>
                    {x.priority || 'HIGH'} PRIORITY
                  </Badge>
                  <b>{Math.round(x.gapPercentage || 0)}%</b>
                </div>
              </div>
            ))}
            {!priorityGaps.length && <Empty text="No high priority knowledge gaps identified." />}
          </div>
        </Card>

        <Card>
          <div className="sectionHead">
            <div>
              <h3>Phased Growth Roadmap</h3>
              <p className="muted">Step-by-step milestones to achieve full role readiness.</p>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {learningPath.map((x: any, idx: number) => (
              <div
                key={idx}
                style={{
                  display: 'flex',
                  gap: 14,
                  alignItems: 'flex-start',
                  padding: 14,
                  borderRadius: 12,
                  border: '1px solid var(--border)',
                  background: '#faf9fd',
                }}
              >
                <div
                  style={{
                    display: 'grid',
                    width: 36,
                    height: 36,
                    placeItems: 'center',
                    borderRadius: '50%',
                    background: '#ded7fb',
                    color: '#4331bf',
                    fontWeight: 800,
                    fontSize: '0.95rem',
                    flexShrink: 0,
                  }}
                >
                  {x.phase || idx + 1}
                </div>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                    <b style={{ fontSize: '0.95rem' }}>{x.title}</b>
                    {x.duration && <small className="muted">({x.duration})</small>}
                  </div>
                  <p style={{ margin: 0, fontSize: '0.85rem', color: '#4e485e', lineHeight: 1.4 }}>
                    {x.reason || 'Foundational knowledge milestone.'}
                  </p>
                </div>
              </div>
            ))}
            {!learningPath.length && <Empty text="Learning path will appear after generating recommendations." />}
          </div>
        </Card>
      </div>

      <Card style={{ marginTop: 20 }}>
        <div className="sectionHead">
          <div>
            <h3>Recommended Catalog Courses</h3>
            <p className="muted">Internal training offerings mapped to your AI growth roadmap.</p>
          </div>
        </div>

        <div className="cardGrid">
          {recommendedCourses.map((x: any) => (
            <Card key={x.trainingId} style={{ display: 'flex', flexDirection: 'column' }}>
              <Badge tone="purple">{x.level}</Badge>
              <h4 style={{ fontSize: '1.05rem', margin: '8px 0 4px' }}>{x.trainingName}</h4>
              <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 10px' }}>
                {x.provider} · {x.duration}
              </p>

              <div style={{ display: 'flex', gap: 8, marginTop: 'auto', paddingTop: 12, borderTop: '1px solid var(--border)' }}>
                {x.courseUrl && (
                  <a
                    className="btn secondary"
                    href={x.courseUrl}
                    target="_blank"
                    rel="noreferrer"
                    style={{ flex: 1, textAlign: 'center', padding: '6px 10px', fontSize: '0.8rem', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 4 }}
                  >
                    Syllabus <ExternalLink size={12} />
                  </a>
                )}
                <Button
                  variant="primary"
                  disabled={enrollingId === x.trainingId}
                  onClick={() => handleEnroll(x.trainingId, x.trainingName)}
                  style={{ flex: 1, padding: '6px 10px', fontSize: '0.8rem' }}
                >
                  {enrollingId === x.trainingId ? 'Enrolling…' : 'Enroll'}
                </Button>
              </div>
            </Card>
          ))}
          {!recommendedCourses.length && <Empty text="No recommended courses mapped to these gaps." />}
        </div>
      </Card>
    </>
  );
}
