spring.application.name=organizational-knowledge-gap-platform

# =====================================================
# SERVER
# =====================================================
server.port=${PORT:8080}
server.address=0.0.0.0

# =====================================================
# DATABASE - PostgreSQL
# Local values are used when running on your computer.
# Render will provide DB_URL, DB_USERNAME and DB_PASSWORD.
# =====================================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Okgip_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# SWAGGER
# =====================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# =====================================================
# JWT
# =====================================================
jwt.secret=${JWT_SECRET:ThisIsMySuperSecretJwtKeyForOkipProject2026}
jwt.expiration=${JWT_EXPIRATION:86400000}

# =====================================================
# GOOGLE GEMINI / SPRING AI
# =====================================================
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.ai.google.genai.chat.temperature=0.3

# =====================================================
# FILE UPLOAD
# =====================================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB