import React from "react";
import MentorLayout from "@/components/layout/MentorLayout";
import mentorshipService, { KnowledgeSession, MentorshipRequest } from "@/services/mentorshipService";
import { BarChart3, Star } from "lucide-react";

export default function Analytics(){
 const [requests,setRequests]=React.useState<MentorshipRequest[]>([]);const[sessions,setSessions]=React.useState<KnowledgeSession[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");
 const load=React.useCallback(async()=>{setLoading(true);setError("");try{const[r,s]=await Promise.all([mentorshipService.getMentorRequests(),mentorshipService.getSessions()]);setRequests(r);setSessions(s)}catch(e:any){setError(e?.response?.data?.message||"Unable to load mentorship analytics.")}finally{setLoading(false)}},[]);React.useEffect(()=>{load()},[load]);
 const pending=requests.filter(x=>x.status==="PENDING").length,accepted=requests.filter(x=>x.status==="ACCEPTED").length,rejected=requests.filter(x=>x.status==="REJECTED").length,completed=sessions.filter(x=>x.status==="COMPLETED").length,scheduled=sessions.filter(x=>x.status==="SCHEDULED").length,cancelled=sessions.filter(x=>x.status==="CANCELLED").length;
 const rated=sessions.filter(x=>x.averageRating!=null);const avg=rated.length? rated.reduce((a,x)=>a+(x.averageRating||0),0)/rated.length:null;const acceptance=requests.length?accepted/requests.length*100:0;
 return <MentorLayout title="Mentorship Analytics"><div className="mb-6"><h2 className="text-2xl font-bold text-slate-900">Mentorship Analytics</h2><p className="mt-1 text-slate-500">Metrics calculated from your persisted mentorship requests, sessions and feedback.</p></div>{error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{loading?<State text="Loading analytics..."/>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active Mentees" value={new Set(requests.filter(x=>x.status==="ACCEPTED").map(x=>x.menteeId)).size}/><Metric label="Pending Requests" value={pending}/><Metric label="Completed Sessions" value={completed}/><Metric label="Scheduled Sessions" value={scheduled}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><BarChart3 size={19} className="text-purple-600"/><h3 className="font-bold">Request Overview</h3></div><div className="mt-5 space-y-4"><Line label="Accepted" value={accepted} total={requests.length}/><Line label="Pending" value={pending} total={requests.length}/><Line label="Rejected" value={rejected} total={requests.length}/><p className="pt-2 text-xs text-slate-500">Acceptance rate: <b>{acceptance.toFixed(1)}%</b></p></div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Star size={19} className="text-purple-600"/><h3 className="font-bold">Session Effectiveness</h3></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Metric label="Completed" value={completed}/><Metric label="Cancelled" value={cancelled}/><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Average Rating</p><p className="mt-1 text-xl font-bold">{avg==null?"No ratings":`${avg.toFixed(2)} / 5`}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Rated Sessions</p><p className="mt-1 text-xl font-bold">{rated.length}</p></div></div></section></div></>}</MentorLayout>
}
const Metric=({label,value}:{label:string;value:number|string})=><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div>;
const Line=({label,value,total}:{label:string;value:number;total:number})=><div><div className="flex justify-between text-xs"><span>{label}</span><b>{value}</b></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-purple-500" style={{width:`${total?Math.min(100,value/total*100):0}%`}}/></div></div>;
const State=({text}:{text:string})=><div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">{text}</div>;
