import React from "react";
import MentorLayout from "@/components/layout/MentorLayout";
import notificationService, { NotificationResponse } from "@/services/notificationService";
import { Bell, CheckCheck } from "lucide-react";

export default function Notifications(){
 const [rows,setRows]=React.useState<NotificationResponse[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");const[busy,setBusy]=React.useState<number|null>(null);
 const load=React.useCallback(async()=>{setLoading(true);setError("");try{setRows(await notificationService.getMyNotifications())}catch(e:any){setError(e?.response?.data?.message||"Unable to load notifications.")}finally{setLoading(false)}},[]);React.useEffect(()=>{load()},[load]);
 const read=async(id:number)=>{setBusy(id);try{await notificationService.markAsRead(id);await load()}catch(e:any){setError(e?.response?.data?.message||"Unable to mark notification as read.")}finally{setBusy(null)}};
 const all=async()=>{try{await notificationService.markAllAsRead();await load()}catch(e:any){setError(e?.response?.data?.message||"Unable to mark notifications as read.")}};
 const unread=rows.filter(x=>!x.read).length;
 return <MentorLayout title="Notifications"><div className="mb-6 flex items-end justify-between"><div><h2 className="text-2xl font-bold text-slate-900">Notifications</h2><p className="mt-1 text-slate-500">Mentorship and workspace notifications from the notification service.</p></div>{unread>0&&<button onClick={all} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-semibold"><CheckCheck size={15}/>Mark all read</button>}</div>{error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{loading?<State text="Loading notifications..."/>:!rows.length?<State text="No notifications yet."/>:<div className="space-y-3">{rows.map(n=><div key={n.notificationId} className={`rounded-2xl border p-5 ${n.read?"bg-white border-slate-200":"bg-purple-50/50 border-purple-100"}`}><div className="flex items-start gap-3"><div className="rounded-xl bg-white p-2 text-purple-600"><Bell size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{n.title}</h3>{!n.read&&<span className="rounded-full bg-purple-600 px-2 py-0.5 text-[9px] font-semibold text-white">NEW</span>}</div><p className="mt-1 text-sm text-slate-600">{n.message}</p><p className="mt-2 text-[11px] text-slate-400">{n.type} · {new Date(n.createdAt).toLocaleString()}</p></div>{!n.read&&<button disabled={busy===n.notificationId} onClick={()=>read(n.notificationId)} className="rounded-lg border bg-white px-3 py-2 text-[10px] font-semibold">Read</button>}</div></div>)}</div>}</MentorLayout>
}
const State=({text}:{text:string})=><div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">{text}</div>;
