spring.application.name=organizational-knowledge-gap-platform
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/okgip_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Swagger (fixes 500 error)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=ThisIsMySuperSecretJwtKeyForOkipProject2026
jwt.expiration=86400000
